name:                open-fallingblock
version:             0.1.0.0
license:             GPL-1
license-file:        LICENSE

extra-source-files:
- README.md
- LICENSE

dependencies:
- base >= 4.7 && < 5
- array
- lens
- mtl
- random
- ansi-terminal
- stm

default-extensions:
- TemplateHaskell
- FlexibleContexts
- LambdaCase

library:
  source-dirs: src
  ghc-options:
  - -O2

executables:
  open-fallingblock-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - open-fallingblock

tests:
  open-fallingblock-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - open-fallingblock

